clear;close all;clc;
SNR=5;
%% 1
noisy_file=['noisy_snr',num2str(SNR),'_油烟机'];
enhanced1_file=['noisy_snr',num2str(SNR),'_油烟机_enhanced1'];
enhanced2_file=['noisy_snr',num2str(SNR),'_油烟机_enhanced2'];
omlsa1(noisy_file,enhanced1_file);
omlsa9(noisy_file,enhanced2_file);

clean_path='clean.wav';
noisy_path=[noisy_file,'.wav'];
enhanced1_path=[enhanced1_file,'.wav'];
enhanced2_path=[enhanced2_file,'.wav'];
[clean,~]=audioread(clean_path);
[noisy,~]=audioread(noisy_path);
[enhanced1,~]=audioread(enhanced1_path);
[enhanced2,fs]=audioread(enhanced2_path);
N1=length(clean);
N2=length(noisy);
N3=length(enhanced1);
N4=length(enhanced2);
N=min([N1,N2,N3,N4]);
clean=clean(1:N);
noisy=noisy(1:N);
enhanced1=enhanced1(1:N);
enhanced2=enhanced2(1:N);

snr1=SNR_singlech(clean,noisy);
snr2=SNR_singlech(clean,enhanced1);
snr3=SNR_singlech(clean,enhanced2);
ssnr1=segsnr(clean,noisy,fs);
ssnr2=segsnr(clean,enhanced1,fs);
ssnr3=segsnr(clean,enhanced2,fs);
mse1=mse(clean,noisy);
mse2=mse(clean,enhanced1);
mse3=mse(clean,enhanced2);
lsd1=LogSpectralDistance(clean,noisy,fs);
lsd2=LogSpectralDistance(clean,enhanced1,fs);
lsd3=LogSpectralDistance(clean,enhanced2,fs);
pesq1=pesq(clean_path,noisy_path);
pesq2=pesq(clean_path,enhanced1_path);
pesq3=pesq(clean_path,enhanced2_path);
stoi1=stoi(clean,noisy,fs);
stoi2=stoi(clean,enhanced1,fs);
stoi3=stoi(clean,enhanced2,fs);

j=1;
excel{2,j}='——';excel{3,j}='无';excel{4,j}='有';j=j+1;
excel{1,j}='snr';excel{2,j}=snr1;excel{3,j}=snr2;excel{4,j}=snr3;j=j+1;
excel{1,j}='ssnr';excel{2,j}=ssnr1;excel{3,j}=ssnr2;excel{4,j}=ssnr3;j=j+1;
excel{1,j}='mse';excel{2,j}=mse1;excel{3,j}=mse2;excel{4,j}=mse3;j=j+1;
excel{1,j}='lsd';excel{2,j}=lsd1;excel{3,j}=lsd2;excel{4,j}=lsd3;j=j+1;
excel{1,j}='pesq';excel{2,j}=pesq1;excel{3,j}=pesq2;excel{4,j}=pesq3;j=j+1;
excel{1,j}='stoi';excel{2,j}=stoi1;excel{3,j}=stoi2;excel{4,j}=stoi3;j=j+1;

%% 2
noisy_file=['noisy_snr',num2str(SNR),'_排气扇'];
enhanced1_file=['noisy_snr',num2str(SNR),'_排气扇_enhanced1'];
enhanced2_file=['noisy_snr',num2str(SNR),'_排气扇_enhanced2'];
omlsa1(noisy_file,enhanced1_file);
omlsa9(noisy_file,enhanced2_file);

clean_path='clean.wav';
noisy_path=[noisy_file,'.wav'];
enhanced1_path=[enhanced1_file,'.wav'];
enhanced2_path=[enhanced2_file,'.wav'];
[clean,~]=audioread(clean_path);
[noisy,~]=audioread(noisy_path);
[enhanced1,~]=audioread(enhanced1_path);
[enhanced2,fs]=audioread(enhanced2_path);
N1=length(clean);
N2=length(noisy);
N3=length(enhanced1);
N4=length(enhanced2);
N=min([N1,N2,N3,N4]);
clean=clean(1:N);
noisy=noisy(1:N);
enhanced1=enhanced1(1:N);
enhanced2=enhanced2(1:N);

snr1=SNR_singlech(clean,noisy);
snr2=SNR_singlech(clean,enhanced1);
snr3=SNR_singlech(clean,enhanced2);
ssnr1=segsnr(clean,noisy,fs);
ssnr2=segsnr(clean,enhanced1,fs);
ssnr3=segsnr(clean,enhanced2,fs);
mse1=mse(clean,noisy);
mse2=mse(clean,enhanced1);
mse3=mse(clean,enhanced2);
lsd1=LogSpectralDistance(clean,noisy,fs);
lsd2=LogSpectralDistance(clean,enhanced1,fs);
lsd3=LogSpectralDistance(clean,enhanced2,fs);
pesq1=pesq(clean_path,noisy_path);
pesq2=pesq(clean_path,enhanced1_path);
pesq3=pesq(clean_path,enhanced2_path);
stoi1=stoi(clean,noisy,fs);
stoi2=stoi(clean,enhanced1,fs);
stoi3=stoi(clean,enhanced2,fs);

j=1;
excel{5,j}='——';excel{6,j}='无';excel{7,j}='有';j=j+1;
excel{5,j}=snr1;excel{6,j}=snr2;excel{7,j}=snr3;j=j+1;
excel{5,j}=ssnr1;excel{6,j}=ssnr2;excel{7,j}=ssnr3;j=j+1;
excel{5,j}=mse1;excel{6,j}=mse2;excel{7,j}=mse3;j=j+1;
excel{5,j}=lsd1;excel{6,j}=lsd2;excel{7,j}=lsd3;j=j+1;
excel{5,j}=pesq1;excel{6,j}=pesq2;excel{7,j}=pesq3;j=j+1;
excel{5,j}=stoi1;excel{6,j}=stoi2;excel{7,j}=stoi3;j=j+1;

%% 3
noisy_file=['noisy_snr',num2str(SNR),'_风扇'];
enhanced1_file=['noisy_snr',num2str(SNR),'_风扇_enhanced1'];
enhanced2_file=['noisy_snr',num2str(SNR),'_风扇_enhanced2'];
omlsa1(noisy_file,enhanced1_file);
omlsa9(noisy_file,enhanced2_file);

clean_path='clean.wav';
noisy_path=[noisy_file,'.wav'];
enhanced1_path=[enhanced1_file,'.wav'];
enhanced2_path=[enhanced2_file,'.wav'];
[clean,~]=audioread(clean_path);
[noisy,~]=audioread(noisy_path);
[enhanced1,~]=audioread(enhanced1_path);
[enhanced2,fs]=audioread(enhanced2_path);
N1=length(clean);
N2=length(noisy);
N3=length(enhanced1);
N4=length(enhanced2);
N=min([N1,N2,N3,N4]);
clean=clean(1:N);
noisy=noisy(1:N);
enhanced1=enhanced1(1:N);
enhanced2=enhanced2(1:N);

snr1=SNR_singlech(clean,noisy);
snr2=SNR_singlech(clean,enhanced1);
snr3=SNR_singlech(clean,enhanced2);
ssnr1=segsnr(clean,noisy,fs);
ssnr2=segsnr(clean,enhanced1,fs);
ssnr3=segsnr(clean,enhanced2,fs);
mse1=mse(clean,noisy);
mse2=mse(clean,enhanced1);
mse3=mse(clean,enhanced2);
lsd1=LogSpectralDistance(clean,noisy,fs);
lsd2=LogSpectralDistance(clean,enhanced1,fs);
lsd3=LogSpectralDistance(clean,enhanced2,fs);
pesq1=pesq(clean_path,noisy_path);
pesq2=pesq(clean_path,enhanced1_path);
pesq3=pesq(clean_path,enhanced2_path);
stoi1=stoi(clean,noisy,fs);
stoi2=stoi(clean,enhanced1,fs); 
stoi3=stoi(clean,enhanced2,fs);

j=1;
excel{8,j}='——';excel{9,j}='无';excel{10,j}='有';j=j+1;
excel{8,j}=snr1;excel{9,j}=snr2;excel{10,j}=snr3;j=j+1;
excel{8,j}=ssnr1;excel{9,j}=ssnr2;excel{10,j}=ssnr3;j=j+1;
excel{8,j}=mse1;excel{9,j}=mse2;excel{10,j}=mse3;j=j+1;
excel{8,j}=lsd1;excel{9,j}=lsd2;excel{10,j}=lsd3;j=j+1;
excel{8,j}=pesq1;excel{9,j}=pesq2;excel{10,j}=pesq3;j=j+1;
excel{8,j}=stoi1;excel{9,j}=stoi2;excel{10,j}=stoi3;j=j+1;
%% 4
noisy_file=['noisy_snr',num2str(SNR),'_马路'];
enhanced1_file=['noisy_snr',num2str(SNR),'_马路_enhanced1'];
enhanced2_file=['noisy_snr',num2str(SNR),'_马路_enhanced2'];
omlsa1(noisy_file,enhanced1_file);
omlsa9(noisy_file,enhanced2_file);

clean_path='clean.wav';
noisy_path=[noisy_file,'.wav'];
enhanced1_path=[enhanced1_file,'.wav'];
enhanced2_path=[enhanced2_file,'.wav'];
[clean,~]=audioread(clean_path);
[noisy,~]=audioread(noisy_path);
[enhanced1,~]=audioread(enhanced1_path);
[enhanced2,fs]=audioread(enhanced2_path);
N1=length(clean);
N2=length(noisy);
N3=length(enhanced1);
N4=length(enhanced2);
N=min([N1,N2,N3,N4]);
clean=clean(1:N);
noisy=noisy(1:N);
enhanced1=enhanced1(1:N);
enhanced2=enhanced2(1:N);

snr1=SNR_singlech(clean,noisy);
snr2=SNR_singlech(clean,enhanced1);
snr3=SNR_singlech(clean,enhanced2);
ssnr1=segsnr(clean,noisy,fs);
ssnr2=segsnr(clean,enhanced1,fs);
ssnr3=segsnr(clean,enhanced2,fs);
mse1=mse(clean,noisy);
mse2=mse(clean,enhanced1);
mse3=mse(clean,enhanced2);
lsd1=LogSpectralDistance(clean,noisy,fs);
lsd2=LogSpectralDistance(clean,enhanced1,fs);
lsd3=LogSpectralDistance(clean,enhanced2,fs);
pesq1=pesq(clean_path,noisy_path);
pesq2=pesq(clean_path,enhanced1_path);
pesq3=pesq(clean_path,enhanced2_path);
stoi1=stoi(clean,noisy,fs);
stoi2=stoi(clean,enhanced1,fs);
stoi3=stoi(clean,enhanced2,fs);

j=1;
excel{11,j}='——';excel{12,j}='无';excel{13,j}='有';j=j+1;
excel{11,j}=snr1;excel{12,j}=snr2;excel{13,j}=snr3;j=j+1;
excel{11,j}=ssnr1;excel{12,j}=ssnr2;excel{13,j}=ssnr3;j=j+1;
excel{11,j}=mse1;excel{12,j}=mse2;excel{13,j}=mse3;j=j+1;
excel{11,j}=lsd1;excel{12,j}=lsd2;excel{13,j}=lsd3;j=j+1;
excel{11,j}=pesq1;excel{12,j}=pesq2;excel{13,j}=pesq3;j=j+1;
excel{11,j}=stoi1;excel{12,j}=stoi2;excel{13,j}=stoi3;j=j+1;
%% 5
noisy_file=['noisy_snr',num2str(SNR),'_脚步'];
enhanced1_file=['noisy_snr',num2str(SNR),'_脚步_enhanced1'];
enhanced2_file=['noisy_snr',num2str(SNR),'_脚步_enhanced2'];
omlsa1(noisy_file,enhanced1_file);
omlsa9(noisy_file,enhanced2_file);

clean_path='clean.wav';
noisy_path=[noisy_file,'.wav'];
enhanced1_path=[enhanced1_file,'.wav'];
enhanced2_path=[enhanced2_file,'.wav'];
[clean,~]=audioread(clean_path);
[noisy,~]=audioread(noisy_path);
[enhanced1,~]=audioread(enhanced1_path);
[enhanced2,fs]=audioread(enhanced2_path);
N1=length(clean);
N2=length(noisy);
N3=length(enhanced1);
N4=length(enhanced2);
N=min([N1,N2,N3,N4]);
clean=clean(1:N);
noisy=noisy(1:N);
enhanced1=enhanced1(1:N);
enhanced2=enhanced2(1:N);

snr1=SNR_singlech(clean,noisy);
snr2=SNR_singlech(clean,enhanced1);
snr3=SNR_singlech(clean,enhanced2);
ssnr1=segsnr(clean,noisy,fs);
ssnr2=segsnr(clean,enhanced1,fs);
ssnr3=segsnr(clean,enhanced2,fs);
mse1=mse(clean,noisy);
mse2=mse(clean,enhanced1);
mse3=mse(clean,enhanced2);
lsd1=LogSpectralDistance(clean,noisy,fs);
lsd2=LogSpectralDistance(clean,enhanced1,fs);
lsd3=LogSpectralDistance(clean,enhanced2,fs);
pesq1=pesq(clean_path,noisy_path);
pesq2=pesq(clean_path,enhanced1_path);
pesq3=pesq(clean_path,enhanced2_path);
stoi1=stoi(clean,noisy,fs);
stoi2=stoi(clean,enhanced1,fs);
stoi3=stoi(clean,enhanced2,fs);

j=1;
excel{14,j}='——';excel{15,j}='无';excel{16,j}='有';j=j+1;
excel{14,j}=snr1;excel{15,j}=snr2;excel{16,j}=snr3;j=j+1;
excel{14,j}=ssnr1;excel{15,j}=ssnr2;excel{16,j}=ssnr3;j=j+1;
excel{14,j}=mse1;excel{15,j}=mse2;excel{16,j}=mse3;j=j+1;
excel{14,j}=lsd1;excel{15,j}=lsd2;excel{16,j}=lsd3;j=j+1;
excel{14,j}=pesq1;excel{15,j}=pesq2;excel{16,j}=pesq3;j=j+1;
excel{14,j}=stoi1;excel{15,j}=stoi2;excel{16,j}=stoi3;j=j+1;
%% 6
noisy_file=['noisy_snr',num2str(SNR),'_工厂'];
enhanced1_file=['noisy_snr',num2str(SNR),'_工厂_enhanced1'];
enhanced2_file=['noisy_snr',num2str(SNR),'_工厂_enhanced2'];
omlsa1(noisy_file,enhanced1_file);
omlsa9(noisy_file,enhanced2_file);

clean_path='clean.wav';
noisy_path=[noisy_file,'.wav'];
enhanced1_path=[enhanced1_file,'.wav'];
enhanced2_path=[enhanced2_file,'.wav'];
[clean,~]=audioread(clean_path);
[noisy,~]=audioread(noisy_path);
[enhanced1,~]=audioread(enhanced1_path);
[enhanced2,fs]=audioread(enhanced2_path);
N1=length(clean);
N2=length(noisy);
N3=length(enhanced1);
N4=length(enhanced2);
N=min([N1,N2,N3,N4]);
clean=clean(1:N);
noisy=noisy(1:N);
enhanced1=enhanced1(1:N);
enhanced2=enhanced2(1:N);

snr1=SNR_singlech(clean,noisy);
snr2=SNR_singlech(clean,enhanced1);
snr3=SNR_singlech(clean,enhanced2);
ssnr1=segsnr(clean,noisy,fs);
ssnr2=segsnr(clean,enhanced1,fs);
ssnr3=segsnr(clean,enhanced2,fs);
mse1=mse(clean,noisy);
mse2=mse(clean,enhanced1);
mse3=mse(clean,enhanced2);
lsd1=LogSpectralDistance(clean,noisy,fs);
lsd2=LogSpectralDistance(clean,enhanced1,fs);
lsd3=LogSpectralDistance(clean,enhanced2,fs);
pesq1=pesq(clean_path,noisy_path);
pesq2=pesq(clean_path,enhanced1_path);
pesq3=pesq(clean_path,enhanced2_path);
stoi1=stoi(clean,noisy,fs);
stoi2=stoi(clean,enhanced1,fs);
stoi3=stoi(clean,enhanced2,fs);

j=1;
excel{17,j}='——';excel{18,j}='无';excel{19,j}='有';j=j+1;
excel{17,j}=snr1;excel{18,j}=snr2;excel{19,j}=snr3;j=j+1;
excel{17,j}=ssnr1;excel{18,j}=ssnr2;excel{19,j}=ssnr3;j=j+1;
excel{17,j}=mse1;excel{18,j}=mse2;excel{19,j}=mse3;j=j+1;
excel{17,j}=lsd1;excel{18,j}=lsd2;excel{19,j}=lsd3;j=j+1;
excel{17,j}=pesq1;excel{18,j}=pesq2;excel{19,j}=pesq3;j=j+1;
excel{17,j}=stoi1;excel{18,j}=stoi2;excel{19,j}=stoi3;j=j+1;
%%
% subplot(3,2,1);
% plot(x,y(1:3:end,1),'kx');hold on;plot(x,y(1:3:end,1),'k-');hold on;
% plot(x,y(2:3:end,1),'rx');hold on;plot(x,y(2:3:end,1),'r-');hold on;
% plot(x,y(3:3:end,1),'gx');hold on;plot(x,y(3:3:end,1),'g-');
% xlabel('合成信噪比/dB');
% ylabel('SNR/dB');
% title('SNR');
% subplot(3,2,2);
% plot(x,y(1:3:end,2),'kx');hold on;plot(x,y(1:3:end,2),'k-');hold on;
% plot(x,y(2:3:end,2),'rx');hold on;plot(x,y(2:3:end,2),'r-');hold on;
% plot(x,y(3:3:end,2),'gx');hold on;plot(x,y(3:3:end,2),'g-');
% xlabel('合成信噪比/dB');
% ylabel('SegSNR/dB');
% title('SegSNR');
% legend(' ','——',' ','无瞬态干扰抑制',' ','有瞬态干扰抑制');
% subplot(3,2,3);  
% plot(x,y(1:3:end,3),'kx');hold on;plot(x,y(1:3:end,3),'k-');hold on;
% plot(x,y(2:3:end,3),'rx');hold on;plot(x,y(2:3:end,3),'r-');hold on;
% plot(x,y(3:3:end,3),'gx');hold on;plot(x,y(3:3:end,3),'g-');
% xlabel('合成信噪比/dB');
% ylabel('MSE');
% title('MSE');
% subplot(3,2,4);
% plot(x,y(1:3:end,4),'kx');hold on;plot(x,y(1:3:end,4),'k-');hold on;
% plot(x,y(2:3:end,4),'rx');hold on;plot(x,y(2:3:end,4),'r-');hold on;
% plot(x,y(3:3:end,4),'gx');hold on;plot(x,y(3:3:end,4),'g-');
% xlabel('合成信噪比/dB');
% ylabel('LSD');
% title('LSD');
% subplot(3,2,5);
% plot(x,y(1:3:end,5),'kx');hold on;plot(x,y(1:3:end,5),'k-');hold on;
% plot(x,y(2:3:end,5),'rx');hold on;plot(x,y(2:3:end,5),'r-');hold on;
% plot(x,y(3:3:end,5),'gx');hold on;plot(x,y(3:3:end,5),'g-');
% xlabel('合成信噪比/dB');
% ylabel('PESQ');
% title('PESQ');
% subplot(3,2,6);
% plot(x,y(1:3:end,6),'kx');hold on;plot(x,y(1:3:end,6),'k-');hold on;
% plot(x,y(2:3:end,6),'rx');hold on;plot(x,y(2:3:end,6),'r-');hold on;
% plot(x,y(3:3:end,6),'gx');hold on;plot(x,y(3:3:end,6),'g-');
% xlabel('合成信噪比/dB');
% ylabel('STOI');
% title('STOI');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
x=0:1:5;
x1={'油烟机' '排气扇' '风扇' '马路' ' 脚步' '工厂'};

subplot(3,2,1);
plot(x,cell2mat(excel(3:3:end,2))-cell2mat(excel(2:3:end,2)),'bx');hold on;
plot(x,cell2mat(excel(3:3:end,2))-cell2mat(excel(2:3:end,2)),'b-');hold on;
plot(x,cell2mat(excel(4:3:end,2))-cell2mat(excel(2:3:end,2)),'rx');hold on;
plot(x,cell2mat(excel(4:3:end,2))-cell2mat(excel(2:3:end,2)),'r-');
set(gca,'xtick',x);
set(gca,'xticklabel',x1);
ylabel('△SNR');
title('△SNR');

subplot(3,2,2);
plot(x,cell2mat(excel(3:3:end,3))-cell2mat(excel(2:3:end,3)),'bx');hold on;
plot(x,cell2mat(excel(3:3:end,3))-cell2mat(excel(2:3:end,3)),'b-');hold on;
plot(x,cell2mat(excel(4:3:end,3))-cell2mat(excel(2:3:end,3)),'rx');hold on;
plot(x,cell2mat(excel(4:3:end,3))-cell2mat(excel(2:3:end,3)),'r-');
set(gca,'xtick',x);
set(gca,'xticklabel',x1);
ylabel('△SegSNR');
title('△SegSNR');
legend(' ','无',' ','有');

subplot(3,2,3); 
plot(x,cell2mat(excel(2:3:end,4))-cell2mat(excel(3:3:end,4)),'bx');hold on;
plot(x,cell2mat(excel(2:3:end,4))-cell2mat(excel(3:3:end,4)),'b-');hold on;
plot(x,cell2mat(excel(2:3:end,4))-cell2mat(excel(4:3:end,4)),'rx');hold on;
plot(x,cell2mat(excel(2:3:end,4))-cell2mat(excel(4:3:end,4)),'r-');
set(gca,'xtick',x);
set(gca,'xticklabel',x1);
ylabel('△MSE');
title('△MSE');

subplot(3,2,4);
plot(x,cell2mat(excel(2:3:end,5))-cell2mat(excel(3:3:end,5)),'bx');hold on;
plot(x,cell2mat(excel(2:3:end,5))-cell2mat(excel(3:3:end,5)),'b-');hold on;
plot(x,cell2mat(excel(2:3:end,5))-cell2mat(excel(4:3:end,5)),'rx');hold on;
plot(x,cell2mat(excel(2:3:end,5))-cell2mat(excel(4:3:end,5)),'r-');
set(gca,'xtick',x);
set(gca,'xticklabel',x1);
ylabel('△LSD');
title('△LSD');

subplot(3,2,5);
plot(x,cell2mat(excel(3:3:end,6))-cell2mat(excel(2:3:end,6)),'bx');hold on;
plot(x,cell2mat(excel(3:3:end,6))-cell2mat(excel(2:3:end,6)),'b-');hold on;
plot(x,cell2mat(excel(4:3:end,6))-cell2mat(excel(2:3:end,6)),'rx');hold on;
plot(x,cell2mat(excel(4:3:end,6))-cell2mat(excel(2:3:end,6)),'r-');
set(gca,'xtick',x);
set(gca,'xticklabel',x1);
ylabel('△PESQ');
title('△PESQ');

subplot(3,2,6);
plot(x,cell2mat(excel(3:3:end,7))-cell2mat(excel(2:3:end,7)),'bx');hold on;
plot(x,cell2mat(excel(3:3:end,7))-cell2mat(excel(2:3:end,7)),'b-');hold on;
plot(x,cell2mat(excel(4:3:end,7))-cell2mat(excel(2:3:end,7)),'rx');hold on;
plot(x,cell2mat(excel(4:3:end,7))-cell2mat(excel(2:3:end,7)),'r-');
set(gca,'xtick',x);
set(gca,'xticklabel',x1);
ylabel('△STOI');
title('△STOI');