clear;close all;clc;
SNR=5;

%% 1
noisy_file=['noisy_snr',num2str(SNR),'_油烟机'];
enhanced1_file=['noisy_snr',num2str(SNR),'_油烟机_enhanced1'];
enhanced2_file=['noisy_snr',num2str(SNR),'_油烟机_enhanced2'];
enhanced3_file=['noisy_snr',num2str(SNR),'_油烟机_enhanced3'];
omlsa3(noisy_file,enhanced1_file);
omlsa4(noisy_file,enhanced2_file);
omlsa6(noisy_file,enhanced3_file);

clean_path='clean.wav';
noisy_path=[noisy_file,'.wav'];
enhanced1_path=[enhanced1_file,'.wav'];
enhanced2_path=[enhanced2_file,'.wav'];
enhanced3_path=[enhanced3_file,'.wav'];
[clean,~]=audioread(clean_path);
[noisy,~]=audioread(noisy_path);
[enhanced1,~]=audioread(enhanced1_path);
[enhanced2,~]=audioread(enhanced2_path);
[enhanced3,fs]=audioread(enhanced3_path);
N1=length(clean);
N2=length(noisy);
N3=length(enhanced1);
N4=length(enhanced2);
N5=length(enhanced3);
N=min([N1,N2,N3,N4,N5]);
clean=clean(1:N);
noisy=noisy(1:N);
enhanced1=enhanced1(1:N);
enhanced2=enhanced2(1:N);
enhanced3=enhanced3(1:N);
snr1=SNR_singlech(clean,noisy);
snr2=SNR_singlech(clean,enhanced1);
snr3=SNR_singlech(clean,enhanced2);
snr4=SNR_singlech(clean,enhanced3);
ssnr1=segsnr(clean,noisy,fs);
ssnr2=segsnr(clean,enhanced1,fs);
ssnr3=segsnr(clean,enhanced2,fs);
ssnr4=segsnr(clean,enhanced3,fs);
mse1=mse(clean,noisy);
mse2=mse(clean,enhanced1);
mse3=mse(clean,enhanced2);
mse4=mse(clean,enhanced3);
lsd1=LogSpectralDistance(clean,noisy,fs);
lsd2=LogSpectralDistance(clean,enhanced1,fs);
lsd3=LogSpectralDistance(clean,enhanced2,fs);
lsd4=LogSpectralDistance(clean,enhanced3,fs);
pesq1=pesq(clean_path,noisy_path);
pesq2=pesq(clean_path,enhanced1_path);
pesq3=pesq(clean_path,enhanced2_path);
pesq4=pesq(clean_path,enhanced3_path);
stoi1=stoi(clean,noisy,fs);
stoi2=stoi(clean,enhanced1,fs);
stoi3=stoi(clean,enhanced2,fs);
stoi4=stoi(clean,enhanced3,fs);

j=1;
excel{2,j}='——';excel{3,j}='64';excel{4,j}='128';excel{5,j}='256';j=j+1;
excel{1,j}='snr';excel{2,j}=snr1;excel{3,j}=snr2;excel{4,j}=snr3;excel{5,j}=snr4;j=j+1;
excel{1,j}='ssnr';excel{2,j}=ssnr1;excel{3,j}=ssnr2;excel{4,j}=ssnr3;excel{5,j}=ssnr4;j=j+1;
excel{1,j}='mse';excel{2,j}=mse1;excel{3,j}=mse2;excel{4,j}=mse3;excel{5,j}=mse4;j=j+1;
excel{1,j}='lsd';excel{2,j}=lsd1;excel{3,j}=lsd2;excel{4,j}=lsd3;excel{5,j}=lsd4;j=j+1;
excel{1,j}='pesq';excel{2,j}=pesq1;excel{3,j}=pesq2;excel{4,j}=pesq3;excel{5,j}=pesq4;j=j+1;
excel{1,j}='stoi';excel{2,j}=stoi1;excel{3,j}=stoi2;excel{4,j}=stoi3;excel{5,j}=stoi4;

%% 2
noisy_file=['noisy_snr',num2str(SNR),'_排气扇'];
enhanced1_file=['noisy_snr',num2str(SNR),'_排气扇_enhanced1'];
enhanced2_file=['noisy_snr',num2str(SNR),'_排气扇_enhanced2'];
enhanced3_file=['noisy_snr',num2str(SNR),'_排气扇_enhanced3'];
omlsa3(noisy_file,enhanced1_file);
omlsa4(noisy_file,enhanced2_file);
omlsa6(noisy_file,enhanced3_file);
 
clean_path='clean.wav';
noisy_path=[noisy_file,'.wav'];
enhanced1_path=[enhanced1_file,'.wav'];
enhanced2_path=[enhanced2_file,'.wav'];
enhanced3_path=[enhanced3_file,'.wav'];
[clean,~]=audioread(clean_path);
[noisy,~]=audioread(noisy_path);
[enhanced1,~]=audioread(enhanced1_path);
[enhanced2,~]=audioread(enhanced2_path);
[enhanced3,fs]=audioread(enhanced3_path);
N1=length(clean);
N2=length(noisy);
N3=length(enhanced1);
N4=length(enhanced2);
N5=length(enhanced3);
N=min([N1,N2,N3,N4,N5]);
clean=clean(1:N);
noisy=noisy(1:N);
enhanced1=enhanced1(1:N);
enhanced2=enhanced2(1:N);
enhanced3=enhanced3(1:N);
snr1=SNR_singlech(clean,noisy);
snr2=SNR_singlech(clean,enhanced1);
snr3=SNR_singlech(clean,enhanced2);
snr4=SNR_singlech(clean,enhanced3);
ssnr1=segsnr(clean,noisy,fs);
ssnr2=segsnr(clean,enhanced1,fs);
ssnr3=segsnr(clean,enhanced2,fs);
ssnr4=segsnr(clean,enhanced3,fs);
mse1=mse(clean,noisy);
mse2=mse(clean,enhanced1);
mse3=mse(clean,enhanced2);
mse4=mse(clean,enhanced3);
lsd1=LogSpectralDistance(clean,noisy,fs);
lsd2=LogSpectralDistance(clean,enhanced1,fs);
lsd3=LogSpectralDistance(clean,enhanced2,fs);
lsd4=LogSpectralDistance(clean,enhanced3,fs);
pesq1=pesq(clean_path,noisy_path);
pesq2=pesq(clean_path,enhanced1_path);
pesq3=pesq(clean_path,enhanced2_path);
pesq4=pesq(clean_path,enhanced3_path);
stoi1=stoi(clean,noisy,fs);
stoi2=stoi(clean,enhanced1,fs);
stoi3=stoi(clean,enhanced2,fs);
stoi4=stoi(clean,enhanced3,fs);
 
j=1;
excel{6,j}='——';excel{7,j}='64';excel{8,j}='128';excel{9,j}='256';j=j+1;
excel{1,j}='snr';excel{6,j}=snr1;excel{7,j}=snr2;excel{8,j}=snr3;excel{9,j}=snr4;j=j+1;
excel{1,j}='ssnr';excel{6,j}=ssnr1;excel{7,j}=ssnr2;excel{8,j}=ssnr3;excel{9,j}=ssnr4;j=j+1;
excel{1,j}='mse';excel{6,j}=mse1;excel{7,j}=mse2;excel{8,j}=mse3;excel{9,j}=mse4;j=j+1;
excel{1,j}='lsd';excel{6,j}=lsd1;excel{7,j}=lsd2;excel{8,j}=lsd3;excel{9,j}=lsd4;j=j+1;
excel{1,j}='pesq';excel{6,j}=pesq1;excel{7,j}=pesq2;excel{8,j}=pesq3;excel{9,j}=pesq4;j=j+1;
excel{1,j}='stoi';excel{6,j}=stoi1;excel{7,j}=stoi2;excel{8,j}=stoi3;excel{9,j}=stoi4;

%% 3
noisy_file=['noisy_snr',num2str(SNR),'_风扇'];
enhanced1_file=['noisy_snr',num2str(SNR),'_风扇_enhanced1'];
enhanced2_file=['noisy_snr',num2str(SNR),'_风扇_enhanced2'];
enhanced3_file=['noisy_snr',num2str(SNR),'_风扇_enhanced3'];
omlsa3(noisy_file,enhanced1_file);
omlsa4(noisy_file,enhanced2_file);
omlsa6(noisy_file,enhanced3_file);
 
clean_path='clean.wav';
noisy_path=[noisy_file,'.wav'];
enhanced1_path=[enhanced1_file,'.wav'];
enhanced2_path=[enhanced2_file,'.wav'];
enhanced3_path=[enhanced3_file,'.wav'];
[clean,~]=audioread(clean_path);
[noisy,~]=audioread(noisy_path);
[enhanced1,~]=audioread(enhanced1_path);
[enhanced2,~]=audioread(enhanced2_path);
[enhanced3,fs]=audioread(enhanced3_path);
N1=length(clean);
N2=length(noisy);
N3=length(enhanced1);
N4=length(enhanced2);
N5=length(enhanced3);
N=min([N1,N2,N3,N4,N5]);
clean=clean(1:N);
noisy=noisy(1:N);
enhanced1=enhanced1(1:N);
enhanced2=enhanced2(1:N);
enhanced3=enhanced3(1:N);
snr1=SNR_singlech(clean,noisy);
snr2=SNR_singlech(clean,enhanced1);
snr3=SNR_singlech(clean,enhanced2);
snr4=SNR_singlech(clean,enhanced3);
ssnr1=segsnr(clean,noisy,fs);
ssnr2=segsnr(clean,enhanced1,fs);
ssnr3=segsnr(clean,enhanced2,fs);
ssnr4=segsnr(clean,enhanced3,fs);
mse1=mse(clean,noisy);
mse2=mse(clean,enhanced1);
mse3=mse(clean,enhanced2);
mse4=mse(clean,enhanced3);
lsd1=LogSpectralDistance(clean,noisy,fs);
lsd2=LogSpectralDistance(clean,enhanced1,fs);
lsd3=LogSpectralDistance(clean,enhanced2,fs);
lsd4=LogSpectralDistance(clean,enhanced3,fs);
pesq1=pesq(clean_path,noisy_path);
pesq2=pesq(clean_path,enhanced1_path);
pesq3=pesq(clean_path,enhanced2_path);
pesq4=pesq(clean_path,enhanced3_path);
stoi1=stoi(clean,noisy,fs);
stoi2=stoi(clean,enhanced1,fs);
stoi3=stoi(clean,enhanced2,fs);
stoi4=stoi(clean,enhanced3,fs);
 
j=1;
excel{10,j}='——';excel{11,j}='64';excel{12,j}='128';excel{13,j}='256';j=j+1;
excel{1,j}='snr';excel{10,j}=snr1;excel{11,j}=snr2;excel{12,j}=snr3;excel{13,j}=snr4;j=j+1;
excel{1,j}='ssnr';excel{10,j}=ssnr1;excel{11,j}=ssnr2;excel{12,j}=ssnr3;excel{13,j}=ssnr4;j=j+1;
excel{1,j}='mse';excel{10,j}=mse1;excel{11,j}=mse2;excel{12,j}=mse3;excel{13,j}=mse4;j=j+1;
excel{1,j}='lsd';excel{10,j}=lsd1;excel{11,j}=lsd2;excel{12,j}=lsd3;excel{13,j}=lsd4;j=j+1;
excel{1,j}='pesq';excel{10,j}=pesq1;excel{11,j}=pesq2;excel{12,j}=pesq3;excel{13,j}=pesq4;j=j+1;
excel{1,j}='stoi';excel{10,j}=stoi1;excel{11,j}=stoi2;excel{12,j}=stoi3;excel{13,j}=stoi4;

%% 4
noisy_file=['noisy_snr',num2str(SNR),'_马路'];
enhanced1_file=['noisy_snr',num2str(SNR),'_马路_enhanced1'];
enhanced2_file=['noisy_snr',num2str(SNR),'_马路_enhanced2'];
enhanced3_file=['noisy_snr',num2str(SNR),'_马路_enhanced3'];
omlsa3(noisy_file,enhanced1_file);
omlsa4(noisy_file,enhanced2_file);
omlsa6(noisy_file,enhanced3_file);
 
clean_path='clean.wav';
noisy_path=[noisy_file,'.wav'];
enhanced1_path=[enhanced1_file,'.wav'];
enhanced2_path=[enhanced2_file,'.wav'];
enhanced3_path=[enhanced3_file,'.wav'];
[clean,~]=audioread(clean_path);
[noisy,~]=audioread(noisy_path);
[enhanced1,~]=audioread(enhanced1_path);
[enhanced2,~]=audioread(enhanced2_path);
[enhanced3,fs]=audioread(enhanced3_path);
N1=length(clean);
N2=length(noisy);
N3=length(enhanced1);
N4=length(enhanced2);
N5=length(enhanced3);
N=min([N1,N2,N3,N4,N5]);
clean=clean(1:N);
noisy=noisy(1:N);
enhanced1=enhanced1(1:N);
enhanced2=enhanced2(1:N);
enhanced3=enhanced3(1:N);
snr1=SNR_singlech(clean,noisy);
snr2=SNR_singlech(clean,enhanced1);
snr3=SNR_singlech(clean,enhanced2);
snr4=SNR_singlech(clean,enhanced3);
ssnr1=segsnr(clean,noisy,fs);
ssnr2=segsnr(clean,enhanced1,fs);
ssnr3=segsnr(clean,enhanced2,fs);
ssnr4=segsnr(clean,enhanced3,fs);
mse1=mse(clean,noisy);
mse2=mse(clean,enhanced1);
mse3=mse(clean,enhanced2);
mse4=mse(clean,enhanced3);
lsd1=LogSpectralDistance(clean,noisy,fs);
lsd2=LogSpectralDistance(clean,enhanced1,fs);
lsd3=LogSpectralDistance(clean,enhanced2,fs);
lsd4=LogSpectralDistance(clean,enhanced3,fs);
pesq1=pesq(clean_path,noisy_path);
pesq2=pesq(clean_path,enhanced1_path);
pesq3=pesq(clean_path,enhanced2_path);
pesq4=pesq(clean_path,enhanced3_path);
stoi1=stoi(clean,noisy,fs);
stoi2=stoi(clean,enhanced1,fs);
stoi3=stoi(clean,enhanced2,fs);
stoi4=stoi(clean,enhanced3,fs);
 
j=1;
excel{14,j}='——';excel{15,j}='64';excel{16,j}='128';excel{17,j}='256';j=j+1;
excel{1,j}='snr';excel{14,j}=snr1;excel{15,j}=snr2;excel{16,j}=snr3;excel{17,j}=snr4;j=j+1;
excel{1,j}='ssnr';excel{14,j}=ssnr1;excel{15,j}=ssnr2;excel{16,j}=ssnr3;excel{17,j}=ssnr4;j=j+1;
excel{1,j}='mse';excel{14,j}=mse1;excel{15,j}=mse2;excel{16,j}=mse3;excel{17,j}=mse4;j=j+1;
excel{1,j}='lsd';excel{14,j}=lsd1;excel{15,j}=lsd2;excel{16,j}=lsd3;excel{17,j}=lsd4;j=j+1;
excel{1,j}='pesq';excel{14,j}=pesq1;excel{15,j}=pesq2;excel{16,j}=pesq3;excel{17,j}=pesq4;j=j+1;
excel{1,j}='stoi';excel{14,j}=stoi1;excel{15,j}=stoi2;excel{16,j}=stoi3;excel{17,j}=stoi4;

%% 5
noisy_file=['noisy_snr',num2str(SNR),'_脚步'];
enhanced1_file=['noisy_snr',num2str(SNR),'_脚步_enhanced1'];
enhanced2_file=['noisy_snr',num2str(SNR),'_脚步_enhanced2'];
enhanced3_file=['noisy_snr',num2str(SNR),'_脚步_enhanced3'];
omlsa3(noisy_file,enhanced1_file);
omlsa4(noisy_file,enhanced2_file);
omlsa6(noisy_file,enhanced3_file);
 
clean_path='clean.wav';
noisy_path=[noisy_file,'.wav'];
enhanced1_path=[enhanced1_file,'.wav'];
enhanced2_path=[enhanced2_file,'.wav'];
enhanced3_path=[enhanced3_file,'.wav'];
[clean,~]=audioread(clean_path);
[noisy,~]=audioread(noisy_path);
[enhanced1,~]=audioread(enhanced1_path);
[enhanced2,~]=audioread(enhanced2_path);
[enhanced3,fs]=audioread(enhanced3_path);
N1=length(clean);
N2=length(noisy);
N3=length(enhanced1);
N4=length(enhanced2);
N5=length(enhanced3);
N=min([N1,N2,N3,N4,N5]);
clean=clean(1:N);
noisy=noisy(1:N);
enhanced1=enhanced1(1:N);
enhanced2=enhanced2(1:N);
enhanced3=enhanced3(1:N);
snr1=SNR_singlech(clean,noisy);
snr2=SNR_singlech(clean,enhanced1);
snr3=SNR_singlech(clean,enhanced2);
snr4=SNR_singlech(clean,enhanced3);
ssnr1=segsnr(clean,noisy,fs);
ssnr2=segsnr(clean,enhanced1,fs);
ssnr3=segsnr(clean,enhanced2,fs);
ssnr4=segsnr(clean,enhanced3,fs);
mse1=mse(clean,noisy);
mse2=mse(clean,enhanced1);
mse3=mse(clean,enhanced2);
mse4=mse(clean,enhanced3);
lsd1=LogSpectralDistance(clean,noisy,fs);
lsd2=LogSpectralDistance(clean,enhanced1,fs);
lsd3=LogSpectralDistance(clean,enhanced2,fs);
lsd4=LogSpectralDistance(clean,enhanced3,fs);
pesq1=pesq(clean_path,noisy_path);
pesq2=pesq(clean_path,enhanced1_path);
pesq3=pesq(clean_path,enhanced2_path);
pesq4=pesq(clean_path,enhanced3_path);
stoi1=stoi(clean,noisy,fs);
stoi2=stoi(clean,enhanced1,fs);
stoi3=stoi(clean,enhanced2,fs);
stoi4=stoi(clean,enhanced3,fs);
 
j=1;
excel{18,j}='——';excel{19,j}='64';excel{20,j}='128';excel{21,j}='256';j=j+1;
excel{1,j}='snr';excel{18,j}=snr1;excel{19,j}=snr2;excel{20,j}=snr3;excel{21,j}=snr4;j=j+1;
excel{1,j}='ssnr';excel{18,j}=ssnr1;excel{19,j}=ssnr2;excel{20,j}=ssnr3;excel{21,j}=ssnr4;j=j+1;
excel{1,j}='mse';excel{18,j}=mse1;excel{19,j}=mse2;excel{20,j}=mse3;excel{21,j}=mse4;j=j+1;
excel{1,j}='lsd';excel{18,j}=lsd1;excel{19,j}=lsd2;excel{20,j}=lsd3;excel{21,j}=lsd4;j=j+1;
excel{1,j}='pesq';excel{18,j}=pesq1;excel{19,j}=pesq2;excel{20,j}=pesq3;excel{21,j}=pesq4;j=j+1;
excel{1,j}='stoi';excel{18,j}=stoi1;excel{19,j}=stoi2;excel{20,j}=stoi3;excel{21,j}=stoi4;

%% 6
noisy_file=['noisy_snr',num2str(SNR),'_工厂'];
enhanced1_file=['noisy_snr',num2str(SNR),'_工厂_enhanced1'];
enhanced2_file=['noisy_snr',num2str(SNR),'_工厂_enhanced2'];
enhanced3_file=['noisy_snr',num2str(SNR),'_工厂_enhanced3'];
omlsa3(noisy_file,enhanced1_file);
omlsa4(noisy_file,enhanced2_file);
omlsa6(noisy_file,enhanced3_file);
 
clean_path='clean.wav';
noisy_path=[noisy_file,'.wav'];
enhanced1_path=[enhanced1_file,'.wav'];
enhanced2_path=[enhanced2_file,'.wav'];
enhanced3_path=[enhanced3_file,'.wav'];
[clean,~]=audioread(clean_path);
[noisy,~]=audioread(noisy_path);
[enhanced1,~]=audioread(enhanced1_path);
[enhanced2,~]=audioread(enhanced2_path);
[enhanced3,fs]=audioread(enhanced3_path);
N1=length(clean);
N2=length(noisy);
N3=length(enhanced1);
N4=length(enhanced2);
N5=length(enhanced3);
N=min([N1,N2,N3,N4,N5]);
clean=clean(1:N);
noisy=noisy(1:N);
enhanced1=enhanced1(1:N);
enhanced2=enhanced2(1:N);
enhanced3=enhanced3(1:N);
snr1=SNR_singlech(clean,noisy);
snr2=SNR_singlech(clean,enhanced1);
snr3=SNR_singlech(clean,enhanced2);
snr4=SNR_singlech(clean,enhanced3);
ssnr1=segsnr(clean,noisy,fs);
ssnr2=segsnr(clean,enhanced1,fs);
ssnr3=segsnr(clean,enhanced2,fs);
ssnr4=segsnr(clean,enhanced3,fs);
mse1=mse(clean,noisy);
mse2=mse(clean,enhanced1);
mse3=mse(clean,enhanced2);
mse4=mse(clean,enhanced3);
lsd1=LogSpectralDistance(clean,noisy,fs);
lsd2=LogSpectralDistance(clean,enhanced1,fs);
lsd3=LogSpectralDistance(clean,enhanced2,fs);
lsd4=LogSpectralDistance(clean,enhanced3,fs);
pesq1=pesq(clean_path,noisy_path);
pesq2=pesq(clean_path,enhanced1_path);
pesq3=pesq(clean_path,enhanced2_path);
pesq4=pesq(clean_path,enhanced3_path);
stoi1=stoi(clean,noisy,fs);
stoi2=stoi(clean,enhanced1,fs);
stoi3=stoi(clean,enhanced2,fs);
stoi4=stoi(clean,enhanced3,fs);
 
j=1;
excel{22,j}='——';excel{23,j}='64';excel{24,j}='128';excel{25,j}='256';j=j+1;
excel{1,j}='snr';excel{22,j}=snr1;excel{23,j}=snr2;excel{24,j}=snr3;excel{25,j}=snr4;j=j+1;
excel{1,j}='ssnr';excel{22,j}=ssnr1;excel{23,j}=ssnr2;excel{24,j}=ssnr3;excel{25,j}=ssnr4;j=j+1;
excel{1,j}='mse';excel{22,j}=mse1;excel{23,j}=mse2;excel{24,j}=mse3;excel{25,j}=mse4;j=j+1;
excel{1,j}='lsd';excel{22,j}=lsd1;excel{23,j}=lsd2;excel{24,j}=lsd3;excel{25,j}=lsd4;j=j+1;
excel{1,j}='pesq';excel{22,j}=pesq1;excel{23,j}=pesq2;excel{24,j}=pesq3;excel{25,j}=pesq4;j=j+1;
excel{1,j}='stoi';excel{22,j}=stoi1;excel{23,j}=stoi2;excel{24,j}=stoi3;excel{25,j}=stoi4;

%%
x=0:1:5;
x1={'油烟机' '排气扇' '风扇' '马路' ' 脚步' '工厂'};

subplot(3,2,1);
plot(x,cell2mat(excel(3:4:end,2))-cell2mat(excel(2:4:end,2)),'kx');hold on;
plot(x,cell2mat(excel(3:4:end,2))-cell2mat(excel(2:4:end,2)),'k-');hold on;
plot(x,cell2mat(excel(4:4:end,2))-cell2mat(excel(2:4:end,2)),'cx');hold on;
plot(x,cell2mat(excel(4:4:end,2))-cell2mat(excel(2:4:end,2)),'c-');hold on;
plot(x,cell2mat(excel(5:4:end,2))-cell2mat(excel(2:4:end,2)),'rx');hold on;
plot(x,cell2mat(excel(5:4:end,2))-cell2mat(excel(2:4:end,2)),'r-');
set(gca,'xtick',x);
set(gca,'xticklabel',x1);
ylabel('△SNR');
title('△SNR');

subplot(3,2,2);
plot(x,cell2mat(excel(3:4:end,3))-cell2mat(excel(2:4:end,3)),'kx');hold on;
plot(x,cell2mat(excel(3:4:end,3))-cell2mat(excel(2:4:end,3)),'k-');hold on;
plot(x,cell2mat(excel(4:4:end,3))-cell2mat(excel(2:4:end,3)),'cx');hold on;
plot(x,cell2mat(excel(4:4:end,3))-cell2mat(excel(2:4:end,3)),'c-');hold on;
plot(x,cell2mat(excel(5:4:end,3))-cell2mat(excel(2:4:end,3)),'rx');hold on;
plot(x,cell2mat(excel(5:4:end,3))-cell2mat(excel(2:4:end,3)),'r-');
set(gca,'xtick',x);
set(gca,'xticklabel',x1);
ylabel('△SegSNR');
title('△SegSNR');
legend(' ','1',' ','2',' ','3');

subplot(3,2,3); 
plot(x,cell2mat(excel(2:4:end,4))-cell2mat(excel(3:4:end,4)),'kx');hold on;
plot(x,cell2mat(excel(2:4:end,4))-cell2mat(excel(3:4:end,4)),'k-');hold on;
plot(x,cell2mat(excel(2:4:end,4))-cell2mat(excel(4:4:end,4)),'cx');hold on;
plot(x,cell2mat(excel(2:4:end,4))-cell2mat(excel(4:4:end,4)),'c-');hold on;
plot(x,cell2mat(excel(2:4:end,4))-cell2mat(excel(5:4:end,4)),'rx');hold on;
plot(x,cell2mat(excel(2:4:end,4))-cell2mat(excel(5:4:end,4)),'r-');
set(gca,'xtick',x);
set(gca,'xticklabel',x1);
ylabel('△MSE');
title('△MSE');

subplot(3,2,4);
plot(x,cell2mat(excel(2:4:end,5))-cell2mat(excel(3:4:end,5)),'kx');hold on;
plot(x,cell2mat(excel(2:4:end,5))-cell2mat(excel(3:4:end,5)),'k-');hold on;
plot(x,cell2mat(excel(2:4:end,5))-cell2mat(excel(4:4:end,5)),'cx');hold on;
plot(x,cell2mat(excel(2:4:end,5))-cell2mat(excel(4:4:end,5)),'c-');hold on;
plot(x,cell2mat(excel(2:4:end,5))-cell2mat(excel(5:4:end,5)),'rx');hold on;
plot(x,cell2mat(excel(2:4:end,5))-cell2mat(excel(5:4:end,5)),'r-');
set(gca,'xtick',x);
set(gca,'xticklabel',x1);
ylabel('△LSD');
title('△LSD');

subplot(3,2,5);
plot(x,cell2mat(excel(3:4:end,6))-cell2mat(excel(2:4:end,6)),'kx');hold on;
plot(x,cell2mat(excel(3:4:end,6))-cell2mat(excel(2:4:end,6)),'k-');hold on;
plot(x,cell2mat(excel(4:4:end,6))-cell2mat(excel(2:4:end,6)),'cx');hold on;
plot(x,cell2mat(excel(4:4:end,6))-cell2mat(excel(2:4:end,6)),'c-');hold on;
plot(x,cell2mat(excel(5:4:end,6))-cell2mat(excel(2:4:end,6)),'rx');hold on;
plot(x,cell2mat(excel(5:4:end,6))-cell2mat(excel(2:4:end,6)),'r-');
set(gca,'xtick',x);
set(gca,'xticklabel',x1);
ylabel('△PESQ');
title('△PESQ');

subplot(3,2,6);
plot(x,cell2mat(excel(3:4:end,7))-cell2mat(excel(2:4:end,7)),'kx');hold on;
plot(x,cell2mat(excel(3:4:end,7))-cell2mat(excel(2:4:end,7)),'k-');hold on;
plot(x,cell2mat(excel(4:4:end,7))-cell2mat(excel(2:4:end,7)),'cx');hold on;
plot(x,cell2mat(excel(4:4:end,7))-cell2mat(excel(2:4:end,7)),'c-');hold on;
plot(x,cell2mat(excel(5:4:end,7))-cell2mat(excel(2:4:end,7)),'rx');hold on;
plot(x,cell2mat(excel(5:4:end,7))-cell2mat(excel(2:4:end,7)),'r-');
set(gca,'xtick',x);
set(gca,'xticklabel',x1);
ylabel('△STOI');
title('△STOI');