% 一次降噪
clc;clear;close all;
noise_name='工厂';
fs=16000;
excel{1,1}='';excel{1,2}='snr';excel{1,3}='ssnr';excel{1,4}='llr';excel{1,5}='lsd';excel{1,6}='wss';excel{1,7}='pesq';

%% 
clean_path='clean.wav';
noisy_name=['noisy_snr0_',noise_name];
noisy_path=[noisy_name,'.wav'];

enhanced1_path=[noisy_name,'_enhanced1.wav'];
enhanced2_path=[noisy_name,'_enhanced2.wav'];
enhanced3_path=[noisy_name,'_enhanced3.wav'];
enhanced4_path=[noisy_name,'_enhanced4.wav'];
enhanced5_path=[noisy_name,'_enhanced5.wav'];
enhanced1_name=[noisy_name,'_enhanced1'];
enhanced2_name=[noisy_name,'_enhanced2'];
enhanced3_name=[noisy_name,'_enhanced3'];
enhanced4_name=[noisy_name,'_enhanced4'];
enhanced5_name=[noisy_name,'_enhanced5'];
omlsa1(noisy_name,enhanced1_name);
omlsa2(noisy_name,enhanced2_name);
omlsa7(noisy_name,enhanced3_name);
omlsa9(noisy_name,enhanced4_name);
omlsa10(noisy_name,enhanced5_name);
[clean,~]=audioread(clean_path);
[noisy,~]=audioread(noisy_path);
[enhanced1,~]=audioread(enhanced1_path);
[enhanced2,~]=audioread(enhanced2_path);
[enhanced3,~]=audioread(enhanced3_path);
[enhanced4,~]=audioread(enhanced4_path);
[enhanced5,~]=audioread(enhanced5_path);
N1=length(clean);
N2=length(noisy);
N3=length(enhanced1);
N4=length(enhanced2);
N5=length(enhanced3);
N6=length(enhanced4);
N7=length(enhanced5);
N=min([N1,N2,N3,N4,N5,N6,N7]);
clean=clean(1:N);
noisy=noisy(1:N);
enhanced1=enhanced1(1:N);
enhanced2=enhanced2(1:N);
enhanced3=enhanced3(1:N);
enhanced4=enhanced4(1:N);
enhanced5=enhanced5(1:N);

snr1=SNR_singlech(clean,noisy);
snr2=SNR_singlech(clean,enhanced1);
snr3=SNR_singlech(clean,enhanced2);
snr4=SNR_singlech(clean,enhanced3);
snr5=SNR_singlech(clean,enhanced4);
snr6=SNR_singlech(clean,enhanced5);
ssnr1=segsnr(clean,noisy,fs);
ssnr2=segsnr(clean,enhanced1,fs);
ssnr3=segsnr(clean,enhanced2,fs);
ssnr4=segsnr(clean,enhanced3,fs);
ssnr5=segsnr(clean,enhanced4,fs);
ssnr6=segsnr(clean,enhanced5,fs);
llr1=comp_llr(clean_path,noisy_path);
llr2=comp_llr(clean_path,enhanced1_path);
llr3=comp_llr(clean_path,enhanced2_path);
llr4=comp_llr(clean_path,enhanced3_path);
llr5=comp_llr(clean_path,enhanced4_path);
llr6=comp_llr(clean_path,enhanced5_path);
lsd1=LogSpectralDistance(clean,noisy,fs);
lsd2=LogSpectralDistance(clean,enhanced1,fs);
lsd3=LogSpectralDistance(clean,enhanced2,fs);
lsd4=LogSpectralDistance(clean,enhanced3,fs);
lsd5=LogSpectralDistance(clean,enhanced4,fs);
lsd6=LogSpectralDistance(clean,enhanced5,fs);
wss1=comp_wss(clean_path,noisy_path);
wss2=comp_wss(clean_path,enhanced1_path);
wss3=comp_wss(clean_path,enhanced2_path);
wss4=comp_wss(clean_path,enhanced3_path);
wss5=comp_wss(clean_path,enhanced4_path);
wss6=comp_wss(clean_path,enhanced5_path);
pesq1=pesq(clean_path,noisy_path);
pesq2=pesq(clean_path,enhanced1_path);
pesq3=pesq(clean_path,enhanced2_path);
pesq4=pesq(clean_path,enhanced3_path);
pesq5=pesq(clean_path,enhanced4_path);
pesq6=pesq(clean_path,enhanced5_path);

i=2;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr1;j=j+1;
excel{i,j}=ssnr1;j=j+1;
excel{i,j}=llr1;j=j+1;
excel{i,j}=lsd1;j=j+1;
excel{i,j}=wss1;j=j+1;
excel{i,j}=pesq1;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr2;j=j+1;
excel{i,j}=ssnr2;j=j+1;
excel{i,j}=llr2;j=j+1;
excel{i,j}=lsd2;j=j+1;
excel{i,j}=wss2;j=j+1;
excel{i,j}=pesq2;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr3;j=j+1;
excel{i,j}=ssnr3;j=j+1;
excel{i,j}=llr3;j=j+1;
excel{i,j}=lsd3;j=j+1;
excel{i,j}=wss3;j=j+1;
excel{i,j}=pesq3;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr4;j=j+1;
excel{i,j}=ssnr4;j=j+1;
excel{i,j}=llr4;j=j+1;
excel{i,j}=lsd4;j=j+1;
excel{i,j}=wss4;j=j+1;
excel{i,j}=pesq4;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr5;j=j+1;
excel{i,j}=ssnr5;j=j+1;
excel{i,j}=llr5;j=j+1;
excel{i,j}=lsd5;j=j+1;
excel{i,j}=wss5;j=j+1;
excel{i,j}=pesq5;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr6;j=j+1;
excel{i,j}=ssnr6;j=j+1;
excel{i,j}=llr6;j=j+1;
excel{i,j}=lsd6;j=j+1;
excel{i,j}=wss6;j=j+1;
excel{i,j}=pesq6;

%% 
clean_path='clean.wav';
noisy_name=['noisy_snr5_',noise_name];
noisy_path=[noisy_name,'.wav'];
enhanced1_path=[noisy_name,'_enhanced1.wav'];
enhanced2_path=[noisy_name,'_enhanced2.wav'];
enhanced3_path=[noisy_name,'_enhanced3.wav'];
enhanced4_path=[noisy_name,'_enhanced4.wav'];
enhanced5_path=[noisy_name,'_enhanced5.wav'];
enhanced1_name=[noisy_name,'_enhanced1'];
enhanced2_name=[noisy_name,'_enhanced2'];
enhanced3_name=[noisy_name,'_enhanced3'];
enhanced4_name=[noisy_name,'_enhanced4'];
enhanced5_name=[noisy_name,'_enhanced5'];
omlsa1(noisy_name,enhanced1_name);
omlsa7(noisy_name,enhanced2_name);
omlsa8(noisy_name,enhanced3_name);
omlsa9(noisy_name,enhanced4_name);
omlsa10(noisy_name,enhanced5_name);
[clean,~]=audioread(clean_path);
[noisy,~]=audioread(noisy_path);
[enhanced1,~]=audioread(enhanced1_path);
[enhanced2,~]=audioread(enhanced2_path);
[enhanced3,~]=audioread(enhanced3_path);
[enhanced4,~]=audioread(enhanced4_path);
[enhanced5,~]=audioread(enhanced5_path);
N1=length(clean);
N2=length(noisy);
N3=length(enhanced1);
N4=length(enhanced2);
N5=length(enhanced3);
N6=length(enhanced4);
N7=length(enhanced5);
N=min([N1,N2,N3,N4,N5,N6,N7]);
clean=clean(1:N);
noisy=noisy(1:N);
enhanced1=enhanced1(1:N);
enhanced2=enhanced2(1:N);
enhanced3=enhanced3(1:N);
enhanced4=enhanced4(1:N);
enhanced5=enhanced5(1:N);

snr1=SNR_singlech(clean,noisy);
snr2=SNR_singlech(clean,enhanced1);
snr3=SNR_singlech(clean,enhanced2);
snr4=SNR_singlech(clean,enhanced3);
snr5=SNR_singlech(clean,enhanced4);
snr6=SNR_singlech(clean,enhanced5);
ssnr1=segsnr(clean,noisy,fs);
ssnr2=segsnr(clean,enhanced1,fs);
ssnr3=segsnr(clean,enhanced2,fs);
ssnr4=segsnr(clean,enhanced3,fs);
ssnr5=segsnr(clean,enhanced4,fs);
ssnr6=segsnr(clean,enhanced5,fs);
llr1=comp_llr(clean_path,noisy_path);
llr2=comp_llr(clean_path,enhanced1_path);
llr3=comp_llr(clean_path,enhanced2_path);
llr4=comp_llr(clean_path,enhanced3_path);
llr5=comp_llr(clean_path,enhanced4_path);
llr6=comp_llr(clean_path,enhanced5_path);
lsd1=LogSpectralDistance(clean,noisy,fs);
lsd2=LogSpectralDistance(clean,enhanced1,fs);
lsd3=LogSpectralDistance(clean,enhanced2,fs);
lsd4=LogSpectralDistance(clean,enhanced3,fs);
lsd5=LogSpectralDistance(clean,enhanced4,fs);
lsd6=LogSpectralDistance(clean,enhanced5,fs);
wss1=comp_wss(clean_path,noisy_path);
wss2=comp_wss(clean_path,enhanced1_path);
wss3=comp_wss(clean_path,enhanced2_path);
wss4=comp_wss(clean_path,enhanced3_path);
wss5=comp_wss(clean_path,enhanced4_path);
wss6=comp_wss(clean_path,enhanced5_path);
pesq1=pesq(clean_path,noisy_path);
pesq2=pesq(clean_path,enhanced1_path);
pesq3=pesq(clean_path,enhanced2_path);
pesq4=pesq(clean_path,enhanced3_path);
pesq5=pesq(clean_path,enhanced4_path);
pesq6=pesq(clean_path,enhanced5_path);

i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr1;j=j+1;
excel{i,j}=ssnr1;j=j+1;
excel{i,j}=llr1;j=j+1;
excel{i,j}=lsd1;j=j+1;
excel{i,j}=wss1;j=j+1;
excel{i,j}=pesq1;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr2;j=j+1;
excel{i,j}=ssnr2;j=j+1;
excel{i,j}=llr2;j=j+1;
excel{i,j}=lsd2;j=j+1;
excel{i,j}=wss2;j=j+1;
excel{i,j}=pesq2;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr3;j=j+1;
excel{i,j}=ssnr3;j=j+1;
excel{i,j}=llr3;j=j+1;
excel{i,j}=lsd3;j=j+1;
excel{i,j}=wss3;j=j+1;
excel{i,j}=pesq3;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr4;j=j+1;
excel{i,j}=ssnr4;j=j+1;
excel{i,j}=llr4;j=j+1;
excel{i,j}=lsd4;j=j+1;
excel{i,j}=wss4;j=j+1;
excel{i,j}=pesq4;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr5;j=j+1;
excel{i,j}=ssnr5;j=j+1;
excel{i,j}=llr5;j=j+1;
excel{i,j}=lsd5;j=j+1;
excel{i,j}=wss5;j=j+1;
excel{i,j}=pesq5;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr6;j=j+1;
excel{i,j}=ssnr6;j=j+1;
excel{i,j}=llr6;j=j+1;
excel{i,j}=lsd6;j=j+1;
excel{i,j}=wss6;j=j+1;
excel{i,j}=pesq6;

%% 
clean_path='clean.wav';
noisy_name=['noisy_snr10_',noise_name];
noisy_path=[noisy_name,'.wav'];
enhanced1_path=[noisy_name,'_enhanced1.wav'];
enhanced2_path=[noisy_name,'_enhanced2.wav'];
enhanced3_path=[noisy_name,'_enhanced3.wav'];
enhanced4_path=[noisy_name,'_enhanced4.wav'];
enhanced5_path=[noisy_name,'_enhanced5.wav'];
enhanced1_name=[noisy_name,'_enhanced1'];
enhanced2_name=[noisy_name,'_enhanced2'];
enhanced3_name=[noisy_name,'_enhanced3'];
enhanced4_name=[noisy_name,'_enhanced4'];
enhanced5_name=[noisy_name,'_enhanced5'];
omlsa1(noisy_name,enhanced1_name);
omlsa7(noisy_name,enhanced2_name);
omlsa8(noisy_name,enhanced3_name);
omlsa9(noisy_name,enhanced4_name);
omlsa10(noisy_name,enhanced5_name);
[clean,~]=audioread(clean_path);
[noisy,~]=audioread(noisy_path);
[enhanced1,~]=audioread(enhanced1_path);
[enhanced2,~]=audioread(enhanced2_path);
[enhanced3,~]=audioread(enhanced3_path);
[enhanced4,~]=audioread(enhanced4_path);
[enhanced5,~]=audioread(enhanced5_path);
N1=length(clean);
N2=length(noisy);
N3=length(enhanced1);
N4=length(enhanced2);
N5=length(enhanced3);
N6=length(enhanced4);
N7=length(enhanced5);
N=min([N1,N2,N3,N4,N5,N6,N7]);
clean=clean(1:N);
noisy=noisy(1:N);
enhanced1=enhanced1(1:N);
enhanced2=enhanced2(1:N);
enhanced3=enhanced3(1:N);
enhanced4=enhanced4(1:N);
enhanced5=enhanced5(1:N);

snr1=SNR_singlech(clean,noisy);
snr2=SNR_singlech(clean,enhanced1);
snr3=SNR_singlech(clean,enhanced2);
snr4=SNR_singlech(clean,enhanced3);
snr5=SNR_singlech(clean,enhanced4);
snr6=SNR_singlech(clean,enhanced5);
ssnr1=segsnr(clean,noisy,fs);
ssnr2=segsnr(clean,enhanced1,fs);
ssnr3=segsnr(clean,enhanced2,fs);
ssnr4=segsnr(clean,enhanced3,fs);
ssnr5=segsnr(clean,enhanced4,fs);
ssnr6=segsnr(clean,enhanced5,fs);
llr1=comp_llr(clean_path,noisy_path);
llr2=comp_llr(clean_path,enhanced1_path);
llr3=comp_llr(clean_path,enhanced2_path);
llr4=comp_llr(clean_path,enhanced3_path);
llr5=comp_llr(clean_path,enhanced4_path);
llr6=comp_llr(clean_path,enhanced5_path);
lsd1=LogSpectralDistance(clean,noisy,fs);
lsd2=LogSpectralDistance(clean,enhanced1,fs);
lsd3=LogSpectralDistance(clean,enhanced2,fs);
lsd4=LogSpectralDistance(clean,enhanced3,fs);
lsd5=LogSpectralDistance(clean,enhanced4,fs);
lsd6=LogSpectralDistance(clean,enhanced5,fs);
wss1=comp_wss(clean_path,noisy_path);
wss2=comp_wss(clean_path,enhanced1_path);
wss3=comp_wss(clean_path,enhanced2_path);
wss4=comp_wss(clean_path,enhanced3_path);
wss5=comp_wss(clean_path,enhanced4_path);
wss6=comp_wss(clean_path,enhanced5_path);
pesq1=pesq(clean_path,noisy_path);
pesq2=pesq(clean_path,enhanced1_path);
pesq3=pesq(clean_path,enhanced2_path);
pesq4=pesq(clean_path,enhanced3_path);
pesq5=pesq(clean_path,enhanced4_path);
pesq6=pesq(clean_path,enhanced5_path);

i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr1;j=j+1;
excel{i,j}=ssnr1;j=j+1;
excel{i,j}=llr1;j=j+1;
excel{i,j}=lsd1;j=j+1;
excel{i,j}=wss1;j=j+1;
excel{i,j}=pesq1;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr2;j=j+1;
excel{i,j}=ssnr2;j=j+1;
excel{i,j}=llr2;j=j+1;
excel{i,j}=lsd2;j=j+1;
excel{i,j}=wss2;j=j+1;
excel{i,j}=pesq2;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr3;j=j+1;
excel{i,j}=ssnr3;j=j+1;
excel{i,j}=llr3;j=j+1;
excel{i,j}=lsd3;j=j+1;
excel{i,j}=wss3;j=j+1;
excel{i,j}=pesq3;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr4;j=j+1;
excel{i,j}=ssnr4;j=j+1;
excel{i,j}=llr4;j=j+1;
excel{i,j}=lsd4;j=j+1;
excel{i,j}=wss4;j=j+1;
excel{i,j}=pesq4;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr5;j=j+1;
excel{i,j}=ssnr5;j=j+1;
excel{i,j}=llr5;j=j+1;
excel{i,j}=lsd5;j=j+1;
excel{i,j}=wss5;j=j+1;
excel{i,j}=pesq5;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr6;j=j+1;
excel{i,j}=ssnr6;j=j+1;
excel{i,j}=llr6;j=j+1;
excel{i,j}=lsd6;j=j+1;
excel{i,j}=wss6;j=j+1;
excel{i,j}=pesq6;

%% 
clean_path='clean.wav';
noisy_name=['noisy_snr15_',noise_name];
noisy_path=[noisy_name,'.wav'];
enhanced1_path=[noisy_name,'_enhanced1.wav'];
enhanced2_path=[noisy_name,'_enhanced2.wav'];
enhanced3_path=[noisy_name,'_enhanced3.wav'];
enhanced4_path=[noisy_name,'_enhanced4.wav'];
enhanced5_path=[noisy_name,'_enhanced5.wav'];
enhanced1_name=[noisy_name,'_enhanced1'];
enhanced2_name=[noisy_name,'_enhanced2'];
enhanced3_name=[noisy_name,'_enhanced3'];
enhanced4_name=[noisy_name,'_enhanced4'];
enhanced5_name=[noisy_name,'_enhanced5'];
omlsa1(noisy_name,enhanced1_name);
omlsa7(noisy_name,enhanced2_name);
omlsa8(noisy_name,enhanced3_name);
omlsa9(noisy_name,enhanced4_name);
omlsa10(noisy_name,enhanced5_name);
[clean,~]=audioread(clean_path);
[noisy,~]=audioread(noisy_path);
[enhanced1,~]=audioread(enhanced1_path);
[enhanced2,~]=audioread(enhanced2_path);
[enhanced3,~]=audioread(enhanced3_path);
[enhanced4,~]=audioread(enhanced4_path);
[enhanced5,~]=audioread(enhanced5_path);
N1=length(clean);
N2=length(noisy);
N3=length(enhanced1);
N4=length(enhanced2);
N5=length(enhanced3);
N6=length(enhanced4);
N7=length(enhanced5);
N=min([N1,N2,N3,N4,N5,N6,N7]);
clean=clean(1:N);
noisy=noisy(1:N);
enhanced1=enhanced1(1:N);
enhanced2=enhanced2(1:N);
enhanced3=enhanced3(1:N);
enhanced4=enhanced4(1:N);
enhanced5=enhanced5(1:N);

snr1=SNR_singlech(clean,noisy);
snr2=SNR_singlech(clean,enhanced1);
snr3=SNR_singlech(clean,enhanced2);
snr4=SNR_singlech(clean,enhanced3);
snr5=SNR_singlech(clean,enhanced4);
snr6=SNR_singlech(clean,enhanced5);
ssnr1=segsnr(clean,noisy,fs);
ssnr2=segsnr(clean,enhanced1,fs);
ssnr3=segsnr(clean,enhanced2,fs);
ssnr4=segsnr(clean,enhanced3,fs);
ssnr5=segsnr(clean,enhanced4,fs);
ssnr6=segsnr(clean,enhanced5,fs);
llr1=comp_llr(clean_path,noisy_path);
llr2=comp_llr(clean_path,enhanced1_path);
llr3=comp_llr(clean_path,enhanced2_path);
llr4=comp_llr(clean_path,enhanced3_path);
llr5=comp_llr(clean_path,enhanced4_path);
llr6=comp_llr(clean_path,enhanced5_path);
lsd1=LogSpectralDistance(clean,noisy,fs);
lsd2=LogSpectralDistance(clean,enhanced1,fs);
lsd3=LogSpectralDistance(clean,enhanced2,fs);
lsd4=LogSpectralDistance(clean,enhanced3,fs);
lsd5=LogSpectralDistance(clean,enhanced4,fs);
lsd6=LogSpectralDistance(clean,enhanced5,fs);
wss1=comp_wss(clean_path,noisy_path);
wss2=comp_wss(clean_path,enhanced1_path);
wss3=comp_wss(clean_path,enhanced2_path);
wss4=comp_wss(clean_path,enhanced3_path);
wss5=comp_wss(clean_path,enhanced4_path);
wss6=comp_wss(clean_path,enhanced5_path);
pesq1=pesq(clean_path,noisy_path);
pesq2=pesq(clean_path,enhanced1_path);
pesq3=pesq(clean_path,enhanced2_path);
pesq4=pesq(clean_path,enhanced3_path);
pesq5=pesq(clean_path,enhanced4_path);
pesq6=pesq(clean_path,enhanced5_path);

i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr1;j=j+1;
excel{i,j}=ssnr1;j=j+1;
excel{i,j}=llr1;j=j+1;
excel{i,j}=lsd1;j=j+1;
excel{i,j}=wss1;j=j+1;
excel{i,j}=pesq1;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr2;j=j+1;
excel{i,j}=ssnr2;j=j+1;
excel{i,j}=llr2;j=j+1;
excel{i,j}=lsd2;j=j+1;
excel{i,j}=wss2;j=j+1;
excel{i,j}=pesq2;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr3;j=j+1;
excel{i,j}=ssnr3;j=j+1;
excel{i,j}=llr3;j=j+1;
excel{i,j}=lsd3;j=j+1;
excel{i,j}=wss3;j=j+1;
excel{i,j}=pesq3;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr4;j=j+1;
excel{i,j}=ssnr4;j=j+1;
excel{i,j}=llr4;j=j+1;
excel{i,j}=lsd4;j=j+1;
excel{i,j}=wss4;j=j+1;
excel{i,j}=pesq4;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr5;j=j+1;
excel{i,j}=ssnr5;j=j+1;
excel{i,j}=llr5;j=j+1;
excel{i,j}=lsd5;j=j+1;
excel{i,j}=wss5;j=j+1;
excel{i,j}=pesq5;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr6;j=j+1;
excel{i,j}=ssnr6;j=j+1;
excel{i,j}=llr6;j=j+1;
excel{i,j}=lsd6;j=j+1;
excel{i,j}=wss6;j=j+1;
excel{i,j}=pesq6;

%% 
x=[0,5,10,15];
subplot(3,2,1);
plot(x,cell2mat(excel(3:6:21,2))-cell2mat(excel(2:6:20,2)),'m-');hold on;
plot(x,cell2mat(excel(4:6:22,2))-cell2mat(excel(2:6:20,2)),'k-');hold on;
plot(x,cell2mat(excel(5:6:23,2))-cell2mat(excel(2:6:20,2)),'b-');hold on;
plot(x,cell2mat(excel(6:6:24,2))-cell2mat(excel(2:6:20,2)),'g-');hold on;
plot(x,cell2mat(excel(7:6:25,2))-cell2mat(excel(2:6:20,2)),'r-');hold on;
plot(x,cell2mat(excel(3:6:21,2))-cell2mat(excel(2:6:20,2)),'mx');hold on;
plot(x,cell2mat(excel(4:6:22,2))-cell2mat(excel(2:6:20,2)),'kx');hold on;
plot(x,cell2mat(excel(5:6:23,2))-cell2mat(excel(2:6:20,2)),'bx');hold on;
plot(x,cell2mat(excel(6:6:24,2))-cell2mat(excel(2:6:20,2)),'gx');hold on;
plot(x,cell2mat(excel(7:6:25,2))-cell2mat(excel(2:6:20,2)),'rx');
xlabel('合成信噪比/dB');
ylabel('△SNR');
title('△SNR');
 
subplot(3,2,2);
plot(x,cell2mat(excel(3:6:21,3))-cell2mat(excel(2:6:20,3)),'m-');hold on;
plot(x,cell2mat(excel(4:6:22,3))-cell2mat(excel(2:6:20,3)),'k-');hold on;
plot(x,cell2mat(excel(5:6:23,3))-cell2mat(excel(2:6:20,3)),'b-');hold on;
plot(x,cell2mat(excel(6:6:24,3))-cell2mat(excel(2:6:20,3)),'g-');hold on;
plot(x,cell2mat(excel(7:6:25,3))-cell2mat(excel(2:6:20,3)),'r-');hold on;
plot(x,cell2mat(excel(3:6:21,3))-cell2mat(excel(2:6:20,3)),'mx');hold on;
plot(x,cell2mat(excel(4:6:22,3))-cell2mat(excel(2:6:20,3)),'kx');hold on;
plot(x,cell2mat(excel(5:6:23,3))-cell2mat(excel(2:6:20,3)),'bx');hold on;
plot(x,cell2mat(excel(6:6:24,3))-cell2mat(excel(2:6:20,3)),'gx');hold on;
plot(x,cell2mat(excel(7:6:25,3))-cell2mat(excel(2:6:20,3)),'rx');
legend('IMCRA-OMLSA','SA\_IMCRA-OMLSA','SER\_IMCRA-OMLSA','TD\_IMCRA-OMSLA','CI\_IMCRA-OMLSA');
xlabel('合成信噪比/dB');
ylabel('△SegSNR');
title('△SegSNR');
 
subplot(3,2,3);
plot(x,cell2mat(excel(2:6:20,4))-cell2mat(excel(3:6:21,4)),'mx');hold on;
plot(x,cell2mat(excel(2:6:20,4))-cell2mat(excel(3:6:21,4)),'m-');hold on;
plot(x,cell2mat(excel(2:6:20,4))-cell2mat(excel(4:6:22,4)),'kx');hold on;
plot(x,cell2mat(excel(2:6:20,4))-cell2mat(excel(4:6:22,4)),'k-');hold on;
plot(x,cell2mat(excel(2:6:20,4))-cell2mat(excel(5:6:23,4)),'bx');hold on;
plot(x,cell2mat(excel(2:6:20,4))-cell2mat(excel(5:6:23,4)),'b-');hold on;
plot(x,cell2mat(excel(2:6:20,4))-cell2mat(excel(6:6:24,4)),'gx');hold on;
plot(x,cell2mat(excel(2:6:20,4))-cell2mat(excel(6:6:24,4)),'g-');hold on;
plot(x,cell2mat(excel(2:6:20,4))-cell2mat(excel(7:6:25,4)),'rx');hold on;
plot(x,cell2mat(excel(2:6:20,4))-cell2mat(excel(7:6:25,4)),'r-');
xlabel('合成信噪比/dB');
ylabel('△LLR');
title('△LLR');
 
subplot(3,2,4);
plot(x,cell2mat(excel(2:6:20,5))-cell2mat(excel(3:6:21,5)),'mx');hold on;
plot(x,cell2mat(excel(2:6:20,5))-cell2mat(excel(3:6:21,5)),'m-');hold on;
plot(x,cell2mat(excel(2:6:20,5))-cell2mat(excel(4:6:22,5)),'kx');hold on;
plot(x,cell2mat(excel(2:6:20,5))-cell2mat(excel(4:6:22,5)),'k-');hold on;
plot(x,cell2mat(excel(2:6:20,5))-cell2mat(excel(5:6:23,5)),'bx');hold on;
plot(x,cell2mat(excel(2:6:20,5))-cell2mat(excel(5:6:23,5)),'b-');hold on;
plot(x,cell2mat(excel(2:6:20,5))-cell2mat(excel(6:6:24,5)),'gx');hold on;
plot(x,cell2mat(excel(2:6:20,5))-cell2mat(excel(6:6:24,5)),'g-');hold on;
plot(x,cell2mat(excel(2:6:20,5))-cell2mat(excel(7:6:25,5)),'rx');hold on;
plot(x,cell2mat(excel(2:6:20,5))-cell2mat(excel(7:6:25,5)),'r-');
xlabel('合成信噪比/dB');
ylabel('△LSD');
title('△LSD');
 
subplot(3,2,5);
plot(x,cell2mat(excel(2:6:20,6))-cell2mat(excel(3:6:21,6)),'mx');hold on;
plot(x,cell2mat(excel(2:6:20,6))-cell2mat(excel(3:6:21,6)),'m-');hold on;
plot(x,cell2mat(excel(2:6:20,6))-cell2mat(excel(4:6:22,6)),'kx');hold on;
plot(x,cell2mat(excel(2:6:20,6))-cell2mat(excel(4:6:22,6)),'k-');hold on;
plot(x,cell2mat(excel(2:6:20,6))-cell2mat(excel(5:6:23,6)),'bx');hold on;
plot(x,cell2mat(excel(2:6:20,6))-cell2mat(excel(5:6:23,6)),'b-');hold on;
plot(x,cell2mat(excel(2:6:20,6))-cell2mat(excel(6:6:24,6)),'gx');hold on;
plot(x,cell2mat(excel(2:6:20,6))-cell2mat(excel(6:6:24,6)),'g-');hold on;
plot(x,cell2mat(excel(2:6:20,6))-cell2mat(excel(7:6:25,6)),'rx');hold on;
plot(x,cell2mat(excel(2:6:20,6))-cell2mat(excel(7:6:25,6)),'r-');
xlabel('合成信噪比/dB');
ylabel('△WSS');
title('△WSS');
 
subplot(3,2,6);
plot(x,cell2mat(excel(3:6:21,7))-cell2mat(excel(2:6:20,7)),'mx');hold on;
plot(x,cell2mat(excel(3:6:21,7))-cell2mat(excel(2:6:20,7)),'m-');hold on;
plot(x,cell2mat(excel(4:6:22,7))-cell2mat(excel(2:6:20,7)),'kx');hold on;
plot(x,cell2mat(excel(4:6:22,7))-cell2mat(excel(2:6:20,7)),'k-');hold on;
plot(x,cell2mat(excel(5:6:23,7))-cell2mat(excel(2:6:20,7)),'bx');hold on;
plot(x,cell2mat(excel(5:6:23,7))-cell2mat(excel(2:6:20,7)),'b-');hold on;
plot(x,cell2mat(excel(6:6:24,7))-cell2mat(excel(2:6:20,7)),'gx');hold on;
plot(x,cell2mat(excel(6:6:24,7))-cell2mat(excel(2:6:20,7)),'g-');hold on;
plot(x,cell2mat(excel(7:6:25,7))-cell2mat(excel(2:6:20,7)),'rx');hold on;
plot(x,cell2mat(excel(7:6:25,7))-cell2mat(excel(2:6:20,7)),'r-');
xlabel('合成信噪比/dB');
ylabel('△PESQ');
title('△PESQ');

