% 一次降噪
clc;clear;close all;
noise_name='工厂';
fs=16000;
excel{1,1}='';excel{1,2}='snr';excel{1,3}='ssnr';excel{1,4}='llr';excel{1,5}='lsd';excel{1,6}='wss';excel{1,7}='pesq';

%% 
clean_path='clean.wav';
noisy_name=['noisy_snr0_',noise_name];
noisy_path=[noisy_name,'.wav'];

enhanced1_path=[noisy_name,'_enhanced1.wav'];
enhanced2_path=[noisy_name,'_enhanced2.wav'];
enhanced1_name=[noisy_name,'_enhanced1'];
enhanced2_name=[noisy_name,'_enhanced2'];
omlsa1(noisy_name,enhanced1_name);
omlsa7(noisy_name,enhanced2_name);
[clean,~]=audioread(clean_path);
[noisy,~]=audioread(noisy_path);
[enhanced1,~]=audioread(enhanced1_path);
[enhanced2,~]=audioread(enhanced2_path);
N1=length(clean);
N2=length(noisy);
N3=length(enhanced1);
N4=length(enhanced2);
N=min([N1,N2,N3,N4]);
clean=clean(1:N);
noisy=noisy(1:N);
enhanced1=enhanced1(1:N);
enhanced2=enhanced2(1:N);

snr1=SNR_singlech(clean,noisy);
snr2=SNR_singlech(clean,enhanced1);
snr3=SNR_singlech(clean,enhanced2);
ssnr1=segsnr(clean,noisy,fs);
ssnr2=segsnr(clean,enhanced1,fs);
ssnr3=segsnr(clean,enhanced2,fs);
llr1=comp_llr(clean_path,noisy_path);
llr2=comp_llr(clean_path,enhanced1_path);
llr3=comp_llr(clean_path,enhanced2_path);
lsd1=LogSpectralDistance(clean,noisy,fs);
lsd2=LogSpectralDistance(clean,enhanced1,fs);
lsd3=LogSpectralDistance(clean,enhanced2,fs);
wss1=comp_wss(clean_path,noisy_path);
wss2=comp_wss(clean_path,enhanced1_path);
wss3=comp_wss(clean_path,enhanced2_path);
pesq1=pesq(clean_path,noisy_path);
pesq2=pesq(clean_path,enhanced1_path);
pesq3=pesq(clean_path,enhanced2_path);

i=2;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr2-snr1;j=j+1;
excel{i,j}=ssnr2-ssnr1;j=j+1;
excel{i,j}=llr1-llr2;j=j+1;
excel{i,j}=lsd1-lsd2;j=j+1;
excel{i,j}=wss1-wss2;j=j+1;
excel{i,j}=pesq2-pesq1;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr3-snr1;j=j+1;
excel{i,j}=ssnr3-ssnr1;j=j+1;
excel{i,j}=llr1-llr3;j=j+1;
excel{i,j}=lsd1-lsd3;j=j+1;
excel{i,j}=wss1-wss3;j=j+1;
excel{i,j}=pesq3-pesq1;

%% 
clean_path='clean.wav';
noisy_name=['noisy_snr5_',noise_name];
noisy_path=[noisy_name,'.wav'];

enhanced1_path=[noisy_name,'_enhanced1.wav'];
enhanced2_path=[noisy_name,'_enhanced2.wav'];
enhanced1_name=[noisy_name,'_enhanced1'];
enhanced2_name=[noisy_name,'_enhanced2'];
omlsa1(noisy_name,enhanced1_name);
omlsa7(noisy_name,enhanced2_name);
[clean,~]=audioread(clean_path);
[noisy,~]=audioread(noisy_path);
[enhanced1,~]=audioread(enhanced1_path);
[enhanced2,~]=audioread(enhanced2_path);
N1=length(clean);
N2=length(noisy);
N3=length(enhanced1);
N4=length(enhanced2);
N=min([N1,N2,N3,N4]);
clean=clean(1:N);
noisy=noisy(1:N);
enhanced1=enhanced1(1:N);
enhanced2=enhanced2(1:N);

snr1=SNR_singlech(clean,noisy);
snr2=SNR_singlech(clean,enhanced1);
snr3=SNR_singlech(clean,enhanced2);
ssnr1=segsnr(clean,noisy,fs);
ssnr2=segsnr(clean,enhanced1,fs);
ssnr3=segsnr(clean,enhanced2,fs);
llr1=comp_llr(clean_path,noisy_path);
llr2=comp_llr(clean_path,enhanced1_path);
llr3=comp_llr(clean_path,enhanced2_path);
lsd1=LogSpectralDistance(clean,noisy,fs);
lsd2=LogSpectralDistance(clean,enhanced1,fs);
lsd3=LogSpectralDistance(clean,enhanced2,fs);
wss1=comp_wss(clean_path,noisy_path);
wss2=comp_wss(clean_path,enhanced1_path);
wss3=comp_wss(clean_path,enhanced2_path);
pesq1=pesq(clean_path,noisy_path);
pesq2=pesq(clean_path,enhanced1_path);
pesq3=pesq(clean_path,enhanced2_path);

i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr2-snr1;j=j+1;
excel{i,j}=ssnr2-ssnr1;j=j+1;
excel{i,j}=llr1-llr2;j=j+1;
excel{i,j}=lsd1-lsd2;j=j+1;
excel{i,j}=wss1-wss2;j=j+1;
excel{i,j}=pesq2-pesq1;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr3-snr1;j=j+1;
excel{i,j}=ssnr3-ssnr1;j=j+1;
excel{i,j}=llr1-llr3;j=j+1;
excel{i,j}=lsd1-lsd3;j=j+1;
excel{i,j}=wss1-wss3;j=j+1;
excel{i,j}=pesq3-pesq1;

%% 
clean_path='clean.wav';
noisy_name=['noisy_snr10_',noise_name];
noisy_path=[noisy_name,'.wav'];

enhanced1_path=[noisy_name,'_enhanced1.wav'];
enhanced2_path=[noisy_name,'_enhanced2.wav'];
enhanced1_name=[noisy_name,'_enhanced1'];
enhanced2_name=[noisy_name,'_enhanced2'];
omlsa1(noisy_name,enhanced1_name);
omlsa7(noisy_name,enhanced2_name);
[clean,~]=audioread(clean_path);
[noisy,~]=audioread(noisy_path);
[enhanced1,~]=audioread(enhanced1_path);
[enhanced2,~]=audioread(enhanced2_path);
N1=length(clean);
N2=length(noisy);
N3=length(enhanced1);
N4=length(enhanced2);
N=min([N1,N2,N3,N4]);
clean=clean(1:N);
noisy=noisy(1:N);
enhanced1=enhanced1(1:N);
enhanced2=enhanced2(1:N);

snr1=SNR_singlech(clean,noisy);
snr2=SNR_singlech(clean,enhanced1);
snr3=SNR_singlech(clean,enhanced2);
ssnr1=segsnr(clean,noisy,fs);
ssnr2=segsnr(clean,enhanced1,fs);
ssnr3=segsnr(clean,enhanced2,fs);
llr1=comp_llr(clean_path,noisy_path);
llr2=comp_llr(clean_path,enhanced1_path);
llr3=comp_llr(clean_path,enhanced2_path);
lsd1=LogSpectralDistance(clean,noisy,fs);
lsd2=LogSpectralDistance(clean,enhanced1,fs);
lsd3=LogSpectralDistance(clean,enhanced2,fs);
wss1=comp_wss(clean_path,noisy_path);
wss2=comp_wss(clean_path,enhanced1_path);
wss3=comp_wss(clean_path,enhanced2_path);
pesq1=pesq(clean_path,noisy_path);
pesq2=pesq(clean_path,enhanced1_path);
pesq3=pesq(clean_path,enhanced2_path);

i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr2-snr1;j=j+1;
excel{i,j}=ssnr2-ssnr1;j=j+1;
excel{i,j}=llr1-llr2;j=j+1;
excel{i,j}=lsd1-lsd2;j=j+1;
excel{i,j}=wss1-wss2;j=j+1;
excel{i,j}=pesq2-pesq1;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr3-snr1;j=j+1;
excel{i,j}=ssnr3-ssnr1;j=j+1;
excel{i,j}=llr1-llr3;j=j+1;
excel{i,j}=lsd1-lsd3;j=j+1;
excel{i,j}=wss1-wss3;j=j+1;
excel{i,j}=pesq3-pesq1;

%% 
clean_path='clean.wav';
noisy_name=['noisy_snr15_',noise_name];
noisy_path=[noisy_name,'.wav'];

enhanced1_path=[noisy_name,'_enhanced1.wav'];
enhanced2_path=[noisy_name,'_enhanced2.wav'];
enhanced1_name=[noisy_name,'_enhanced1'];
enhanced2_name=[noisy_name,'_enhanced2'];
omlsa1(noisy_name,enhanced1_name);
omlsa7(noisy_name,enhanced2_name);
[clean,~]=audioread(clean_path);
[noisy,~]=audioread(noisy_path);
[enhanced1,~]=audioread(enhanced1_path);
[enhanced2,~]=audioread(enhanced2_path);
N1=length(clean);
N2=length(noisy);
N3=length(enhanced1);
N4=length(enhanced2);
N=min([N1,N2,N3,N4]);
clean=clean(1:N);
noisy=noisy(1:N);
enhanced1=enhanced1(1:N);
enhanced2=enhanced2(1:N);

snr1=SNR_singlech(clean,noisy);
snr2=SNR_singlech(clean,enhanced1);
snr3=SNR_singlech(clean,enhanced2);
ssnr1=segsnr(clean,noisy,fs);
ssnr2=segsnr(clean,enhanced1,fs);
ssnr3=segsnr(clean,enhanced2,fs);
llr1=comp_llr(clean_path,noisy_path);
llr2=comp_llr(clean_path,enhanced1_path);
llr3=comp_llr(clean_path,enhanced2_path);
lsd1=LogSpectralDistance(clean,noisy,fs);
lsd2=LogSpectralDistance(clean,enhanced1,fs);
lsd3=LogSpectralDistance(clean,enhanced2,fs);
wss1=comp_wss(clean_path,noisy_path);
wss2=comp_wss(clean_path,enhanced1_path);
wss3=comp_wss(clean_path,enhanced2_path);
pesq1=pesq(clean_path,noisy_path);
pesq2=pesq(clean_path,enhanced1_path);
pesq3=pesq(clean_path,enhanced2_path);

i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr2-snr1;j=j+1;
excel{i,j}=ssnr2-ssnr1;j=j+1;
excel{i,j}=llr1-llr2;j=j+1;
excel{i,j}=lsd1-lsd2;j=j+1;
excel{i,j}=wss1-wss2;j=j+1;
excel{i,j}=pesq2-pesq1;
i=i+1;
j=1;
excel{i,j}='——';j=j+1;
excel{i,j}=snr3-snr1;j=j+1;
excel{i,j}=ssnr3-ssnr1;j=j+1;
excel{i,j}=llr1-llr3;j=j+1;
excel{i,j}=lsd1-lsd3;j=j+1;
excel{i,j}=wss1-wss3;j=j+1;
excel{i,j}=pesq3-pesq1;

x=[0,5,10,15];
subplot(3,2,1);
plot(x,cell2mat(excel(2:2:8,2)),'k-');hold on;
plot(x,cell2mat(excel(3:2:9,2)),'b-');hold on;
plot(x,cell2mat(excel(2:2:8,2)),'kx');hold on;
plot(x,cell2mat(excel(3:2:9,2)),'bx');
xlabel('合成信噪比/dB');
ylabel('△SNR');
title('△SNR');
 
subplot(3,2,2);
plot(x,cell2mat(excel(2:2:8,3)),'k-');hold on;
plot(x,cell2mat(excel(3:2:9,3)),'b-');hold on;
plot(x,cell2mat(excel(2:2:8,3)),'kx');hold on;
plot(x,cell2mat(excel(3:2:9,3)),'bx');
legend('IMCRA-OMLSA','CI\_IMCRA-OMLSA');
xlabel('合成信噪比/dB');
ylabel('△SegSNR');
title('△SegSNR');
 
subplot(3,2,3);
plot(x,cell2mat(excel(2:2:8,4)),'k-');hold on;
plot(x,cell2mat(excel(3:2:9,4)),'b-');hold on;
plot(x,cell2mat(excel(2:2:8,4)),'kx');hold on;
plot(x,cell2mat(excel(3:2:9,4)),'bx');
xlabel('合成信噪比/dB');
ylabel('△LLR');
title('△LLR');
 
subplot(3,2,4);
plot(x,cell2mat(excel(2:2:8,5)),'k-');hold on;
plot(x,cell2mat(excel(3:2:9,5)),'b-');hold on;
plot(x,cell2mat(excel(2:2:8,5)),'kx');hold on;
plot(x,cell2mat(excel(3:2:9,5)),'bx');
xlabel('合成信噪比/dB');
ylabel('△LSD');
title('△LSD');
 
subplot(3,2,5);
plot(x,cell2mat(excel(2:2:8,6)),'k-');hold on;
plot(x,cell2mat(excel(3:2:9,6)),'b-');hold on;
plot(x,cell2mat(excel(2:2:8,6)),'kx');hold on;
plot(x,cell2mat(excel(3:2:9,6)),'bx');
xlabel('合成信噪比/dB');
ylabel('△WSS');
title('△WSS');
 
subplot(3,2,6);
plot(x,cell2mat(excel(2:2:8,7)),'k-');hold on;
plot(x,cell2mat(excel(3:2:9,7)),'b-');hold on;
plot(x,cell2mat(excel(2:2:8,7)),'kx');hold on;
plot(x,cell2mat(excel(3:2:9,7)),'bx');
xlabel('合成信噪比/dB');
ylabel('△PESQ');
title('△PESQ');